TRANSLATIONS = {
    "en": {
        "app_title": "Price Checker",
        "scan_here": "Scan here",
        "no_product": "No product scanned",
        "scan_history": "Scan History",
        "view_history": "View History",
        "settings": "Settings",
        "submit": "Submit",
        "measurement": "Measurement",
        "price": "Price",
        "special_offer": "SPECIAL OFFER",
        "scan_successful": "Scan successful",
        "error_saving": "Error saving history",
        "settings_saved": "Settings saved successfully",
        "settings_confirm": "Are you really want to open Settings?",
        "yes": "Yes",
        "no": "No",
        "api_url": "API URL",
        "scan_timeout": "Scan Timeout (seconds)",
        "min_length": "Minimum Scan Length",
        "max_length": "Maximum Scan Length",
        "language": "Language",
        "back": "Back",
        "save": "Save",
        "clear_history": "Clear History",
        "no_history": "No history available",
        "clear_confirm": "Are you sure you want to clear history?",
        "scanned": "Scanned",
        "barcode": "Barcode",
        "discount": "Discount",
    },
    "ukr": {
        "app_title": "Перевірка цін",
        "scan_here": "Відскануйте тут",
        "no_product": "Товар не відскановано",
        "scan_history": "Історія сканування",
        "view_history": "Переглянути історію",
        "settings": "Налаштування",
        "submit": "Прийняти",
        "measurement": "Одиниця виміру",
        "price": "Ціна",
        "special_offer": "СПЕЦІАЛЬНА ПРОПОЗИЦІЯ",
        "scan_successful": "Успішно відскановано",
        "error_saving": "Помилка збереження історії",
        "settings_saved": "Налаштування збережено",
        "settings_confirm": "Ви дійсно хочете відкрити Налаштування?",
        "yes": "Так",
        "no": "Ні",
        "api_url": "API URL",
        "scan_timeout": "Час очікування сканування (секунди)",
        "min_length": "Мінімальна довжина сканування",
        "max_length": "Максимальна довжина сканування",
        "language": "Мова",
        "back": "Назад",
        "save": "Зберегти",
        "clear_history": "Очистити історію",
        "no_history": "Історія порожня",
        "clear_confirm": "Ви впевнені, що хочете очистити історію?",
        "scanned": "Відскановано",
        "barcode": "Штрихкод",
        "discount": "Знижка",
    }
} 